apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-emails-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-emails-service
  template:
    metadata:
      labels:
        app: send-emails-service
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
        - name: send-emails-service
          image: stokei/send-emails-service:latest
          resources: {}
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              value: "send-emails"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-password
            - name: DB_OPTIONS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-options
            - name: DB_PREFIX
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-prefix
            - name: DB_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: db-timeout
            - name: QUEUE_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: queue-host
            - name: QUEUE_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: queue-port
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: queue-password
            - name: QUEUE_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: queue-timeout
            - name: MAIL_ID
              valueFrom:
                secretKeyRef:
                  name: send-emails-secret
                  key: mail-id
            - name: MAIL_SECRET
              valueFrom:
                secretKeyRef:
                  name: send-emails-secret
                  key: mail-secret
            - name: MAIL_CONTACT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: send-emails-secret
                  key: mail-contact-email
            - name: MAIL_CONTACT_NAME
              valueFrom:
                secretKeyRef:
                  name: send-emails-secret
                  key: mail-contact-name
            - name: MICROSERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: url
