name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  IMAGE_NAME: send-emails-service
  KUBERNETES_DEPLOYMENT_NAME: send-emails-service-deployment
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  CD:
    name: CD
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{env.CLUSTER_NAME}}

      - name: Deploy to Kubernetes
        run: kubectl apply -f ${{ github.workspace }}/k8s -R
        
      - name: Set image to Kubernetes
        run: kubectl set image deployment/${{env.KUBERNETES_DEPLOYMENT_NAME}} ${{env.IMAGE_NAME}}=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      #- name: Verify deployment
      #  run: kubectl rollout status deployment/${{env.KUBERNETES_DEPLOYMENT_NAME}}